export const documentManagementTableBody = [
  {
    id: 1,
    clientName: "Virgil Kovacek",
    typeOfCase: "TM Opposition",
    documentName: "Document 1",
    tradeMarkNo: "R-3526",
    dateUploaded: "Nov 20, 2024  10:20",
  },
  {
    id: 2,
    clientName: "Beth Schmitt",
    typeOfCase: "Design invalidation",
    documentName: "Document 1",
    tradeMarkNo: "R-3526",
    dateUploaded: "Nov 21, 2024 10:20",
  },
  {
    id: 3,
    clientName: "Clay Hills",
    typeOfCase: "Privacy Violations",
    documentName: "Document 1",
    tradeMarkNo: "R-3526",
    dateUploaded: "Nov 22, 2024 10:20",
  },
  {
    id: 4,
    clientName: "Terry Gleichner",
    typeOfCase: "Employment Disputes",
    documentName: "Document 1",
    tradeMarkNo: "R-3526",
    dateUploaded: "Nov 23, 2024 10:20",
  },
  {
    id: 5,
    clientName: "Cedric Hilpert",
    typeOfCase: "TM Opposition",
    documentName: "Document 1",
    tradeMarkNo: "R-3526",
    dateUploaded: "Nov 24, 2024 10:20",
  },
  {
    id: 6,
    clientName: "Felicia Walsh",
    typeOfCase: "Design invalidation",
    documentName: "Document 1",
    tradeMarkNo: "R-3526",
    dateUploaded: "Nov 25, 2024 10:20",
  },
  {
    id: 7,
    clientName: "Bill Johnson",
    typeOfCase: "Privacy Violations",
    documentName: "Document 1",
    tradeMarkNo: "R-3526",
    dateUploaded: "Nov 26, 2024 10:20",
  },
  {
    id: 8,
    clientName: "Gwen Morar",
    typeOfCase: "Employment Disputes",
    documentName: "Document 1",
    tradeMarkNo: "R-3526",
    dateUploaded: "Nov 27, 2024 10:20",
  },
  {
    id: 9,
    clientName: "Harold Nicolas",
    typeOfCase: "TM Opposition",
    documentName: "Document 1",
    tradeMarkNo: "R-3526",
    dateUploaded: "Nov 28, 2024 10:20",
  },
  {
    id: 10,
    clientName: "Myrtle Kilback",
    typeOfCase: "Design invalidation",
    documentName: "Document 1",
    tradeMarkNo: "R-3526",
    dateUploaded: "Nov 29, 2024 10:20",
  },
  {
    id: 11,
    clientName: "William Greenfelder",
    typeOfCase: "Privacy Violations",
    documentName: "Document 1",
    tradeMarkNo: "R-3526",
    dateUploaded: "Nov 30, 2024 10:20",
  },
  {
    id: 12,
    clientName: "Alberta Parisian",
    typeOfCase: "Employment Disputes",
    documentName: "Document 1",
    tradeMarkNo: "R-3526",
    dateUploaded: "Dec 1, 2024 10:20",
  },
  {
    id: 13,
    clientName: "Charles Kuvalis",
    typeOfCase: "TM Opposition",
    documentName: "Document 1",
    tradeMarkNo: "R-3526",
    dateUploaded: "Dec 2, 2024 10:20",
  },
  {
    id: 14,
    clientName: "Lee White",
    typeOfCase: "Design invalidation",
    documentName: "Document 1",
    tradeMarkNo: "R-3526",
    dateUploaded: "Dec 3, 2024 10:20",
  },
  {
    id: 15,
    clientName: "Simon Cartwright",
    typeOfCase: "Privacy Violations",
    documentName: "Document 1",
    tradeMarkNo: "R-3526",
    dateUploaded: "Dec 4, 2024 10:20",
  },
  {
    id: 16,
    clientName: "April Stroman",
    typeOfCase: "Employment Disputes",
    documentName: "Document 1",
    tradeMarkNo: "R-3526",
    dateUploaded: "Dec 5, 2024 10:20",
  },
];

