export const myCasesTableBody = [
  {
    id: 1,
    typeOfCase: "TM Opposition",
    trademarkName: "Orn - Runolfsson",
    trademarkNumber: "R-3526",
    status: "File Observations",
    statusVariant: "primary",
    nextTask: "Prepare Draft",
    nextTaskVariant: "lightBlue1",
    notes: "Figma ipsum component variant main layer...",
  },
  {
    id: 2,
    typeOfCase: "TM Opposition",
    trademarkName: "Cummings, Reic...",
    trademarkNumber: "R-3526",
    status: "File Invalidation",
    statusVariant: "danger",
    nextTask: "Prepare Evidence",
    nextTaskVariant: "lightBlue2",
    notes: "Figma ipsum component variant main layer...",
  },
  {
    id: 3,
    typeOfCase: "Design invalidation",
    trademarkName: "Crist and Sons",
    trademarkNumber: "R-3526",
    status: "Defense",
    statusVariant: "teal",
    nextTask: "Check Evidence",
    nextTaskVariant: "lightBlue3",
    notes: "Figma ipsum component variant main layer...",
  },
  {
    id: 4,
    typeOfCase: "TM Opposition",
    trademarkName: "Heller - Hoppe",
    trademarkNumber: "R-3526",
    status: "Second Observations",
    statusVariant: "turquoise",
    nextTask: "Client Confirmation",
    nextTaskVariant: "lightBlue4",
    notes: "Figma ipsum component variant main layer...",
  },
  {
    id: 5,
    typeOfCase: "Design invalidation",
    trademarkName: "Lueilwitz LLC",
    trademarkNumber: "R-3526",
    status: "Cooling-Of",
    statusVariant: "orange",
    statusBadge: "47.5",
    nextTask: "Submit",
    nextTaskVariant: "blue1",
    notes: "Figma ipsum component variant main layer...",
  },
  {
    id: 6,
    typeOfCase: "Design invalidation",
    trademarkName: "Lueilwitz LLC",
    trademarkNumber: "R-3526",
    status: "Nogometiers",
    statusVariant: "lime",
    nextTask: "Track",
    nextTaskVariant: "blue2",
    notes: "Figma ipsum component variant main layer...",
  },
];

