export const staffDashboardTableBody = [
  {
    id: 1,
    client: "Kathleen Steuber",
    typeOfCase: "TM Opposition",
    trademarkName: "Orn - Runolfsson",
    trademarkNumber: "R-3526",
    status: "File Observations",
    statusVariant: "primary",
    nextTask: "Prepare Draft",
    nextTaskVariant: "lightBlue1",
    attorney: "PW",
    notes: "Figma ipsum component variant ma...",
  },
  {
    id: 2,
    client: "Rafael Dietrich-...",
    typeOfCase: "Design invalidation",
    trademarkName: "Maggio, Heathco...",
    trademarkNumber: "R-3526",
    status: "File Opposition",
    statusVariant: "danger",
    nextTask: "Check Draft",
    nextTaskVariant: "lightBlue2",
    attorney: "KL",
    notes: "Figma ipsum component variant main layer. List invite group list inspect arrow vector. Select link fill vertical bullet line style undo.",
  },
  {
    id: 3,
    client: "Renee Harber",
    typeOfCase: "TM Opposition",
    trademarkName: "Cummings, Reic...",
    trademarkNumber: "R-3526",
    status: "File Invalidation",
    statusVariant: "danger",
    nextTask: "Prepare Evidence",
    nextTaskVariant: "lightBlue3",
    attorney: "PW",
    notes: "Figma ipsum component variant ma...",
  },
  {
    id: 4,
    client: "Al Cassin",
    typeOfCase: "Design invalidation",
    trademarkName: "Crist and Sons",
    trademarkNumber: "R-3526",
    status: "Defense",
    statusVariant: "teal",
    nextTask: "Check Evidence",
    nextTaskVariant: "lightBlue4",
    attorney: "KL",
    notes: "Figma ipsum component variant ma...",
  },
  {
    id: 5,
    client: "Alberta Herman",
    typeOfCase: "TM Opposition",
    trademarkName: "Heller - Hoppe",
    trademarkNumber: "R-3526",
    status: "Second Observations",
    statusVariant: "turquoise",
    nextTask: "Client Confirmation",
    nextTaskVariant: "blue1",
    attorney: "PW",
    notes: "Figma ipsum component variant ma...",
  },
  {
    id: 6,
    client: "Pete Orn",
    typeOfCase: "Design invalidation",
    trademarkName: "Lueilwitz LLC",
    trademarkNumber: "R-3526",
    status: "Cooling-Off Period",
    statusVariant: "orange",
    nextTask: "Submit",
    nextTaskVariant: "blue2",
    attorney: "KL",
    notes: "Figma ipsum component variant ma...",
  },
  {
    id: 7,
    client: "Pete Orn",
    typeOfCase: "Design invalidation",
    trademarkName: "Lueilwitz LLC",
    trademarkNumber: "R-3526",
    status: "Negotiations",
    statusVariant: "lime",
    nextTask: "Prepare Draft",
    nextTaskVariant: "lightBlue1",
    attorney: "PW",
    notes: "Figma ipsum component variant ma...",
  },
  {
    id: 8,
    client: "Pete Orn",
    typeOfCase: "Design invalidation",
    trademarkName: "Lueilwitz LLC",
    trademarkNumber: "R-3526",
    status: "Second Observations",
    statusVariant: "turquoise",
    nextTask: "Check Draft",
    nextTaskVariant: "lightBlue2",
    attorney: "KL",
    notes: "Figma ipsum component variant ma...",
  },
];

