export const supportManagementTableBody = [
  {
    id: 1,
    clientName: "Virgil Kovacek",
    category: "case update",
    message: "Figma ipsum component va...",
    status: "Pending",
    statusVariant: "in-active",
    received: "Dec 2, 2024",
  },
  {
    id: 2,
    clientName: "Beth Schmitt",
    category: "documentation",
    message: "Figma ipsum component va...",
    status: "Active",
    statusVariant: "success",
    received: "Dec 1, 2024",
  },
  {
    id: 3,
    clientName: "Clay Hills",
    category: "platform feedback",
    message: "Figma ipsum component va...",
    status: "Active",
    statusVariant: "success",
    received: "Nov 26, 2024",
  },
  {
    id: 4,
    clientName: "Terry Gleichner",
    category: "case update",
    message: "Figma ipsum component va...",
    status: "Active",
    statusVariant: "success",
    received: "Nov 30, 2024",
  },
  {
    id: 5,
    clientName: "Cedric Hilpert",
    category: "documentation",
    message: "Figma ipsum component va...",
    status: "Pending",
    statusVariant: "primary",
    received: "Nov 24, 2024",
  },
  {
    id: 6,
    clientName: "Felicia Walsh",
    category: "platform feedback",
    message: "Figma ipsum component va...",
    status: "Pending",
    statusVariant: "primary",
    received: "Dec 3, 2024",
  },
  {
    id: 7,
    clientName: "Bill Johnson",
    category: "case update",
    message: "Figma ipsum component va...",
    status: "Active",
    statusVariant: "success",
    received: "Dec 6, 2024",
  },
  {
    id: 8,
    clientName: "Gwen Morar",
    category: "documentation",
    message: "Figma ipsum component va...",
    status: "Active",
    statusVariant: "success",
    received: "Dec 5, 2024",
  },
  {
    id: 9,
    clientName: "Harold Nicolas",
    category: "platform feedback",
    message: "Figma ipsum component va...",
    status: "Pending",
    statusVariant: "pending",
    received: "Nov 27, 2024",
  },
  {
    id: 10,
    clientName: "Myrtle Kilback",
    category: "case update",
    message: "Figma ipsum component va...",
    status: "Active",
    statusVariant: "success",
    received: "Nov 29, 2024",
  },
];

